import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es' | 'fr' | 'hi' | 'zh' | 'ko' | 'hg' | 'de' | 'ja' | 'it' | 'pt' | 'ru' | 'ar' | 'nl';

/** Flat dot-notation translation map for a single language. */
type TranslationMap = Record<string, string>;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Translation dictionaries
// Keys follow the namespace.key dot-notation agreed in the project spec.
// ─────────────────────────────────────────────────────────────────────────────

const en: TranslationMap = {
  // nav
  'nav.features': 'Features',
  'nav.howItWorks': 'How It Works',
  'nav.pricing': 'Pricing',
  'nav.signIn': 'Sign In',
  'nav.dashboard': 'Dashboard',
  'nav.signOut': 'Sign Out',

  // hero
  'hero.headline': 'Stay Ahead of',
  'hero.subheadline': 'the Machine.',
  'hero.description': 'Subscribe to receive a weekly autonomous technical digest of the most significant AI model releases, framework breakthroughs, and foundation research papers. Curated by specialized agents, delivered directly to your inbox.',
  'hero.emailPlaceholder': 'Enter your email address',
  'hero.ctaButton': 'Get My Briefing',
  'hero.successMessage': 'Successfully subscribed. Welcome.',
  'hero.errorMessage': 'Something went wrong. Please try again.',

  // features
  'features.title': 'Four Agents. One Perfect Brief.',
  'features.subtitle': 'An autonomous pipeline runs every morning so you never miss what matters.',
  'features.badge1': 'Scraper Agent',
  'features.badge2': 'Filter Agent',
  'features.badge3': 'Zero Noise',
  'features.desc1': 'Crawls 200+ sources across ArXiv, GitHub, TechCrunch, and more every morning.',
  'features.desc2': 'Scores each article for relevance, deduplicates, and discards low-signal noise.',
  'features.desc3': 'Delivers only what matches your chosen topics — nothing you did not ask for.',

  // footer
  'footer.tagline': 'Intelligence, delivered daily.',
  'footer.rights': `© ${new Date().getFullYear()} NeuralBrief`,
  'footer.privacyPolicy': 'Privacy Policy',
  'footer.terms': 'Terms of Service',
  'footer.contact': 'Contact',
  'footer.emailPlaceholder': 'email@address.com',
  'footer.ctaButton': 'Subscribed. See you tomorrow.',

  // profile
  'profile.title': 'Your Profile',
  'profile.topics': 'Topics',
  'profile.preferences': 'Preferences',
  'profile.bookmarks': 'Bookmarks',
  'profile.save': 'Save Changes',
  'profile.saving': 'Saving…',
  'profile.saved': 'Saved',
  'profile.logout': 'Log Out',
  'profile.digestFrequency': 'Digest Frequency',
  'profile.daily': 'Daily',
  'profile.weekly': 'Weekly',

  // auth
  'auth.signInWithGoogle': 'Continue with Google',
  'auth.signingIn': 'Signing in…',
  'auth.signOut': 'Sign Out',
  'auth.popupBlocked': 'Pop-up blocked. Please allow pop-ups for this site and try again.',
  'auth.authError': 'Authentication failed. Please try again.',
  'auth.loginRequired': 'Please sign in to continue.',

  // bookmarks
  'bookmarks.title': 'Saved Articles',
  'bookmarks.empty': 'No bookmarks yet. Start reading to save articles here.',
  'bookmarks.remove': 'Remove',
  'bookmarks.loginRequired': 'Sign in to view your bookmarks.',

  // engine
  'engine.title': 'The Pipeline',
  'engine.description': 'Four specialised agents run in sequence every morning at 07:00 UTC.',
  'engine.step1': 'Scraper Agent — harvests fresh articles from 200+ curated sources.',
  'engine.step2': 'Filter Agent — scores relevance and removes duplicates.',
  'engine.step3': 'Summary Agent — distils each article into a two-sentence brief.',
  'engine.step4': 'Email Agent — assembles and sends your personalised digest via Gmail.',

  // faq
  'faq.title': 'Frequently Asked Questions',
  'faq.q1': 'Which topics can I follow?',
  'faq.a1': 'You can tailor your intelligence feed by selecting from our 8 core technical domains, including Data Science, MLOps, AI Research, and Agentic Frameworks. You are free to follow any combination of these topics, and our autonomous pipeline will instantly adjust its scraping targets and filtering weights to prioritize signals that match your exact technical stack.',
  'faq.q2': 'When is the digest delivered?',
  'faq.a2': 'By default, the autonomous pipeline runs its final delivery phase at exactly 07:00 UTC every morning, ensuring the latest global research and releases are in your inbox when you start your day. You can also configure the engine to deliver a consolidated weekly digest every Monday morning via the Preferences dashboard.',
  'faq.q3': 'How do you prevent duplicate articles?',
  'faq.a3': 'Our Evaluation Agent utilizes an advanced vector database to map incoming articles into a high-dimensional semantic space. Before any summary is generated, the agent performs a cosine-similarity check against all recent signals. If two articles report on the exact same model release or paper, the agent automatically deduplicates them and retains only the most technically dense source.',
  'faq.q4': 'Is my Gmail data private?',
  'faq.a4': 'Absolutely. Our pipeline only requires write-only SMTP access to dispatch your briefing directly to your inbox. We utilize strict OAuth 2.0 scopes, meaning our agents physically cannot read, index, or store any of your personal Gmail messages, contacts, or history.',
  'faq.q5': 'Can I change my topics later?',
  'faq.a5': 'Yes, you have full control over your intelligence feed. You can open your personalization dashboard at any time to add new technical domains or remove ones that are no longer relevant to your workflow. The pipeline updates its routing logic instantly, and changes will be reflected in your very next digest.',
  'faq.q6': 'Is NeuralBrief free?',
  'faq.a6': 'Yes, the core daily and weekly autonomous digests are completely free for all engineers and researchers. By subscribing, you gain full access to the personalized intelligence feed, the interactive dashboard, and the daily email briefings at absolutely no cost.',
  'faq.q7': 'How do I unsubscribe?',
  'faq.a7': 'We respect your inbox. Every single digest email contains a one-click unsubscribe link in the footer. Clicking this link immediately halts the delivery pipeline for your address—no login required. Your preferences and data are completely purged from our systems within 24 hours of unsubscribing.',
  'faq.q8': 'How does the Agentic Pipeline actually work?',
  'faq.a8': 'The system relies on a sequential multi-agent architecture. The Ingestion Agent continuously polls RSS, GitHub, and ArXiv. The data is passed to the Evaluation Agent for semantic deduplication. Finally, the Synthesis Agent (powered by Llama 3 and Mistral) abstracts the technical core into concise bullet points before the Delivery Agent dispatches the email.',
  'faq.q9': 'Can I read the raw source documents?',
  'faq.a9': 'Yes. Every summarized signal in your digest and on the dashboard contains a direct citation link back to the original source material. Whether it is a GitHub repository, an ArXiv PDF, or an engineering blog, you can always drill down into the raw data.',
  'faq.q10': 'Which AI models power the Synthesis Agent?',
  'faq.a10': 'We utilize a dynamic, multi-model consensus approach. Depending on the complexity of the source document, the Synthesis Agent dynamically routes tasks between Llama 3 (for rapid extraction), Mistral (for code analysis), and Groq (for ultra-low latency processing) to ensure the highest quality abstraction.',
  'faq.q11': 'How do I access the Developer Dashboard?',
  'faq.a11': 'The Developer Dashboard is a hidden overlay designed for system monitoring. You can access it by pressing Cmd+K (or Ctrl+K) to open the Command Palette, and typing "Developer Dashboard". This provides real-time latency metrics and agent status logs.',
  'faq.q12': 'Can I receive alerts for urgent AI news?',
  'faq.a12': 'Currently, the pipeline is optimized for daily or weekly consolidated delivery to prevent notification fatigue. We intentionally avoid real-time pinging so you can focus on deep work, confident that the engine will summarize everything important by morning.',
  'faq.q13': 'Do you support custom RSS feeds?',
  'faq.a13': 'At this time, the Ingestion Agent relies on a curated internal list of 500+ highly vetted technical sources to guarantee zero noise. However, we are actively developing a feature that will allow enterprise users to inject custom internal wikis and RSS feeds into their private pipelines.',
  'faq.q14': 'How do I change the output language?',
  'faq.a14': 'Our Synthesis Agent natively supports translation into 14 different languages. You can change your preferred output language at any time by accessing the language selector in the main navigation bar. The entire dashboard and your future email digests will instantly adapt to your selection.',

  // cta
  'cta.title': 'Ready for a smarter morning?',
  'cta.subtitle': 'Trusted by engineers at',
  'cta.button': 'Start Free',

  // topics
  'topic_data_science_label': 'Data Science',
  'topic_data_science_desc': 'Statistical frameworks, optimization vectors, and clean visualization architecture. Deep dives into Bayesian methods, causal inference, and large-scale data engineering pipelines.',
  'topic_machine_learning_label': 'Machine Learning',
  'topic_machine_learning_desc': 'Weights, model training pipelines, MLOps orchestration, and edge deployment strategy. Core analysis on gradient descent optimization and distributed training architectures.',
  'topic_ai_research_label': 'AI Research',
  'topic_ai_research_desc': 'Daily ArXiv analysis, foundational breakthroughs, and algorithmic updates. Tracking the bleeding edge of self-supervised learning and multimodal transformer scaling laws.',
  'topic_agentic_ai_label': 'Agentic AI',
  'topic_agentic_ai_desc': 'Multi-agent graphs, autonomous memory layers, and stateful routing architectures. Deep research into ReAct patterns, DSPy optimization, and long-horizon tool use.',
  'topic_mlops_label': 'MLOps',
  'topic_mlops_desc': 'Model deployment, registries, feature stores, CI/CD, and pipeline scalability. Hardened infrastructure reviews covering Kubernetes, Ray clusters, and Triton inference servers.',
  'topic_model_releases_label': 'Model Releases',
  'topic_model_releases_desc': 'Weight releases, open-weights models, benchmarks, and specialized vision/audio fine-tunes. Real-time evaluations of Llama, Mistral, and frontier model capabilities.',
  'topic_ai_industry_label': 'AI Industry',
  'topic_ai_industry_desc': 'Tech news, funding rounds, chip updates, corporate partnerships, and legal landscapes. Macro analysis of GPU supply chains and semiconductor advancements.',
  'topic_tools_libraries_label': 'Tools & Libraries',
  'topic_tools_libraries_desc': 'Developer packages, PyTorch/JS updates, compilers, and local optimization frameworks. Focused updates on CUDA kernels, Triton, and JAX acceleration.',

  // Missing UI keys
  'nav.home': 'Home',
  'nav.digest': 'Digest',
  'nav.topics': 'Topics',
  'nav.profile': 'Profile',
  'nav_domains': 'Domains',
  'nav_engine': 'Pipeline',
  'nav_digest': 'Preview',
  'search_placeholder': 'Search the brief...',
  'focus_overline': 'Focus Domains',
  'focus_title_1': 'Curated signals,',
  'focus_title_2': 'zero noise.',
  'focus_desc': 'We monitor the channels that matter, extracting only actionable technical intelligence.',
  'engine_overline': 'The Engine',
  'engine_title_1': 'Four Agents,',
  'engine_title_2': 'One Pipeline.',
  'engine_desc': 'Our sequence of specialized AI agents runs autonomously every morning at 07:00 UTC.',
  'preview_overline': 'Inbound Signal',
  'preview_title_1': 'Explore the',
  'preview_title_2': 'Daily Stream',
  'cta_title_1': 'Ready to stay',
  'cta_title_2': 'ahead?',
  'cta_desc': 'Receive your daily intelligence digest at 07:00 UTC.',
  'faq_overline': 'FAQ',
  'faq_title_1': 'Frequently Asked',
  'faq_title_2': 'Questions',
  'reading_time': 'min read',
  'cta_success_heading': 'Success!',
  'cta_success_desc': 'You have successfully subscribed to the briefing.',
  'cta_error_invalid_email': 'Please enter a valid email address.',
  'faq_view_all': 'View All Frequently Asked Questions →',
  'faq_subpage_title': 'Knowledge Base',
  'faq_subpage_desc': 'Detailed technical answers on how our autonomous pipeline operates, data privacy, and customization.',
  'faq_back_home': 'Back to Dashboard',
  'engine_consensus_building': 'Building Consensus',
  'engine_consensus_reached': 'Consensus Reached',
  'engine_sources': 'Sources',
  'engine_signals': 'Signals',
  'engine_confidence': 'Confidence',
  'engine_latency': 'Latency',
  'engine_status': 'Status',
  'engine_active': 'Active',
  'engine_standby': 'Standby',
  'engine_task': 'Task',
  'engine_idle': 'Idle',
  'engine_queue': 'Queue',
  'focus_weekly_sync': 'Weekly Sync',
  'profile.loading': 'Loading profile...',
  'focus_read_report': 'Read Full Report',
  'focus_failed_live_feed': 'Failed to load live feed.',
  'footer_sound': 'Sound',
  'footer_sound_on': 'On',
  'footer_sound_off': 'Off',
  'hero.badge': 'NeuralBrief 2.0 / Now Live',
  'hero.title_1': 'Intelligence',
  'hero.title_2': 'Without',
  'hero.title_3': 'The Noise.',
  'hero.desc': 'Our agents continuously monitor, filter, and synthesize the technical web. You get a personalized briefing of only what matters.',
  'hero.ctaPrimary': 'Start Free',
  'hero.ctaSecondary': 'View Example',
  'hero.trustMetrics': 'Used by 10,000+ engineers',
  'hero.trustSources': 'Monitoring 500+ sources',
  'how_step1_title': 'Ingestion',
  'how_step1_desc': 'We continuously aggregate data across thousands of cutting-edge tech blogs, academic journals, open-source repositories, and developer forums, ensuring no crucial signal goes unnoticed.',
  'how_step2_title': 'Filtering',
  'how_step2_desc': 'Our proprietary AI models aggressively filter out marketing fluff, clickbait, and duplicated content, leaving only the high-value technical substance you actually care about.',
  'how_step3_title': 'Synthesis',
  'how_step3_desc': 'Advanced agentic frameworks analyze and connect the dots across multiple sources to synthesize deep, actionable insights and core technical takeaways.',
  'how_step4_title': 'Delivery',
  'how_step4_desc': 'You receive a beautifully formatted, hyper-personalized intelligence digest directly to your inbox or via our dashboard, optimized for rapid comprehension.',
  'how_overline': 'How It Works',
  'how_desc': 'A transparent look at our autonomous intelligence pipeline.',
  'how_metrics_volume': '1.2M+',
  'how_metrics_volume_label': 'Signals Processed Daily',
  'how_metrics_noise': '99.8%',
  'how_metrics_noise_label': 'Noise Reduction',
  'how_metrics_time': '<12ms',
  'how_metrics_time_label': 'Avg Processing Time',
  'how_visual_insight': 'Visual Insight',
  'nav_search_try': 'Try searching for "LLM architecture"',
  'onboarding_welcome_back': 'Welcome Back',
  'onboarding_welcome_title': 'Welcome to NeuralBrief',
  'onboarding_welcome_desc': 'Let\'s set up your personalized intelligence feed.',
  'onboarding_welcome_start': 'Get Started',
  'onboarding_skip': 'Skip Onboarding',
  'onboarding_role_title': 'What is your role?',
  'onboarding_role_desc': 'This helps us tune the technical depth of your briefing.',
  'onboarding_skip_short': 'Skip',
  'onboarding_continue': 'Continue',
  'onboarding_intent_title': 'What are your goals?',
  'onboarding_intent_desc': 'Select what you want to achieve with NeuralBrief.',
  'onboarding_back': 'Back',
  'onboarding_referral_title': 'How did you hear about us?',
  'onboarding_referral_desc': 'We appreciate your feedback.',
  'onboarding_saving': 'Saving profile...',
  'onboarding_done': 'Done',
  'onboarding_done_title': 'You\'re all set!',
  'onboarding_done_desc': 'Your personalized briefing is ready.',
  'topic_openai': 'OpenAI',
  'topic_gemini': 'Gemini',
  'topic_claude': 'Claude',
  'topic_robotics': 'Robotics',
  'topic_startups': 'Startups',
  'personalize_overline': 'Personalization Engine',
  'personalize_headline_1': 'Build Your Own',
  'personalize_headline_2': 'AI Briefing',
  'personalize_desc': 'You control the signal. Select your focus areas and preferred language, and our agents will tailor a feed specifically for your workflow.',
  'personalize_topics': 'Focus Areas',
  'selected': 'Selected',
  'personalize_language': 'Output Language',
  'system_status': 'System Status',
  'personalize_feedback_some': 'NeuralBrief is adapting your feed to prioritize these signals.',
  'personalize_feedback_none': 'Select focus areas to customize your feed.',
  'personalize_relevance': 'Briefing Relevance',
  'confidence': 'Confidence',
  'preview_update': 'Live Update',
  'preview_read_full_doc': 'Read Full Document',
  'preview_failed': 'Failed to load preview.',
  'preview_inbound_stream': 'Inbound Stream',
  'preview_core_engine': 'Core Engine',
  'preview_latest_intel': 'Latest Intel',

  'engine_card1_title': "Ingestion",
  'engine_card1_desc': "Real-time monitoring of ArXiv, GitHub, and RSS.",
  'engine_card2_title': "Evaluation",
  'engine_card2_desc': "Deduplication and vector relevance scoring.",
  'engine_card3_title': "Synthesis",
  'engine_card3_desc': "Consensus modeling for technical abstraction.",
  'engine_card4_title': "Delivery",
  'engine_card4_desc': "Final dispatch via low-latency SMTP.",
  'engine_node_ingestion_title': "Ingestion",
  'engine_node_logicGate_title': "Logic Gate",
  'engine_node_llama_title': "Llama 3",
  'engine_node_mistral_title': "Mistral",
  'engine_node_groq_title': "Groq",
  'engine_node_dispatch_title': "Dispatch",
  'how_title_1': "How We",
  'how_title_2': "Work",
  'preview_tab_all': "All Signals",
  'preview_tab_research': "Research Core",
  'preview_tab_agentic': "Agentic Ops",
  'focus_last_sync': "Last Sync",
  'footer_stay_ahead': "Stay Ahead.",
  'footer_no_noise': "No Noise.",
  'footer_see_tomorrow': "See you tomorrow.",

  // Onboarding
  'onboarding_role_developer': 'Developer',
  'onboarding_role_researcher': 'Researcher',
  'onboarding_role_student': 'Student',
  'onboarding_role_founder': 'Founder',
  'onboarding_role_other': 'Other',
  'onboarding_intent_stay_updated': 'Stay updated on AI',
  'onboarding_intent_deep_research': 'Deep research',
  'onboarding_intent_work_projects': 'Work projects',
  'onboarding_intent_curiosity': 'General curiosity',
  'onboarding_referral_twitter': 'Twitter / X',
  'onboarding_referral_friend': 'A friend',
  'onboarding_referral_google': 'Google Search',
  'onboarding_referral_product_hunt': 'Product Hunt',
  'onboarding_referral_other': 'Other',
  'onboarding_welcome_back': 'Welcome back, {name}',
  'onboarding_welcome_title': 'Setup Your Briefing',
  'onboarding_welcome_desc': 'Tell us a bit about what you do so we can calibrate the technical depth of your feed.',
  'onboarding_welcome_start': 'Start Setup',
  'onboarding_skip': 'Skip for now',
  'onboarding_role_title': 'What is your role?',
  'onboarding_role_desc': 'This helps us tune the technical depth of your briefing.',
  'onboarding_skip_short': 'Skip',
  'onboarding_continue': 'Continue',
  'onboarding_intent_title': 'What is your main goal?',
  'onboarding_intent_desc': 'This helps us select the right types of papers and news.',
  'onboarding_back': 'Back',
  'onboarding_referral_title': 'How did you hear about us?',
  'onboarding_referral_desc': 'We are just curious.',
  'onboarding_saving': 'Saving...',
  'onboarding_done': 'Complete Setup',
  'onboarding_done_title': 'All Set',
  'onboarding_done_desc': 'Your preferences have been saved successfully.',


};

// ─────────────────────────────────────────────────────────────────────────────

const es: TranslationMap = {
  'nav.features': 'Características',
  'nav.howItWorks': 'Cómo funciona',
  'nav.pricing': 'Precios',
  'nav.signIn': 'Iniciar sesión',
  'nav.dashboard': 'Panel',
  'nav.signOut': 'Cerrar sesión',

  'hero.headline': 'Mantente un paso',
  'hero.subheadline': 'adelante.',
  'hero.description': 'Suscríbete para recibir un resumen técnico semanal autónomo sobre los lanzamientos de modelos de IA, avances de frameworks y artículos de investigación fundamentales más significativos. Curado por agentes especializados, directo a tu bandeja de entrada.',
  'hero.emailPlaceholder': 'Introduce tu correo electrónico',
  'hero.ctaButton': 'Recibir mi resumen',
  'hero.successMessage': 'Suscripción correcta. Bienvenido.',
  'hero.errorMessage': 'Algo salió mal. Inténtalo de nuevo.',

  'features.title': 'Cuatro agentes. Un resumen perfecto.',
  'features.subtitle': 'Un proceso autónomo se ejecuta cada mañana para que no te pierdas nada importante.',
  'features.badge1': 'Agente Scraper',
  'features.badge2': 'Agente Filtro',
  'features.badge3': 'Cero ruido',
  'features.desc1': 'Rastrea más de 200 fuentes entre ArXiv, GitHub, TechCrunch y otras cada mañana.',
  'features.desc2': 'Puntúa cada artículo por relevancia, elimina duplicados y descarta el ruido.',
  'features.desc3': 'Entrega solo lo que coincide con tus temas elegidos.',

  'footer.tagline': 'Inteligencia, entregada cada día.',
  'footer.rights': '© 2025 NeuralBrief',
  'footer.privacyPolicy': 'Política de privacidad',
  'footer.terms': 'Términos de servicio',
  'footer.contact': 'Contacto',
  'footer.emailPlaceholder': 'correo@dominio.com',
  'footer.ctaButton': 'Suscrito. Hasta mañana.',

  'profile.title': 'Tu perfil',
  'profile.topics': 'Temas',
  'profile.preferences': 'Preferencias',
  'profile.bookmarks': 'Guardados',
  'profile.save': 'Guardar cambios',
  'profile.saving': 'Guardando…',
  'profile.saved': 'Guardado',
  'profile.logout': 'Cerrar sesión',
  'profile.digestFrequency': 'Frecuencia del resumen',
  'profile.daily': 'Diario',
  'profile.weekly': 'Semanal',

  'auth.signInWithGoogle': 'Continuar con Google',
  'auth.signingIn': 'Iniciando sesión…',
  'auth.signOut': 'Cerrar sesión',
  'auth.popupBlocked': 'Ventana emergente bloqueada. Permite ventanas emergentes e inténtalo de nuevo.',
  'auth.authError': 'Error de autenticación. Inténtalo de nuevo.',
  'auth.loginRequired': 'Por favor, inicia sesión para continuar.',

  'bookmarks.title': 'Artículos guardados',
  'bookmarks.empty': 'Sin marcadores aún. Empieza a leer para guardar artículos aquí.',
  'bookmarks.remove': 'Eliminar',
  'bookmarks.loginRequired': 'Inicia sesión para ver tus marcadores.',

  'engine.title': 'El proceso',
  'engine.description': 'Cuatro agentes especializados se ejecutan en secuencia cada mañana a las 07:00 UTC.',
  'engine.step1': 'Agente Scraper — recopila artículos frescos de más de 200 fuentes.',
  'engine.step2': 'Agente Filtro — puntúa la relevancia y elimina duplicados.',
  'engine.step3': 'Agente Resumen — condensa cada artículo en dos frases.',
  'engine.step4': 'Agente Email — monta y envía tu resumen personalizado por Gmail.',

  'faq.title': 'Preguntas frecuentes',
  'faq.q1': '¿Qué temas puedo seguir?',
  'faq.a1': 'Puedes seguir combinaciones de investigación en IA, lanzamientos de productos, herramientas para desarrolladores, startups, política y más.',
  'faq.q2': '¿Cuándo se entrega el resumen?',
  'faq.a2': 'Los resúmenes se envían a las 07:00 UTC cada mañana, o semanalmente los lunes si lo prefieres.',
  'faq.q3': '¿Cómo se evitan artículos duplicados?',
  'faq.a3': 'El Agente Filtro deduplica por URL y similitud semántica antes de generar los resúmenes.',
  'faq.q4': '¿Son privados mis datos de Gmail?',
  'faq.a4': 'Solo enviamos correos a tu bandeja de entrada — nunca leemos ni almacenamos tus mensajes de Gmail.',
  'faq.q5': '¿Puedo cambiar mis temas más adelante?',
  'faq.a5': 'Sí — abre tu perfil en cualquier momento para añadir o eliminar temas. Los cambios aplican desde el próximo resumen.',
  'faq.q6': '¿Es gratuito NeuralBrief?',
  'faq.a6': 'Sí — el resumen semanal principal es completamente gratuito. Suscríbete con tu correo y empieza a recibir informes sin costo alguno.',
  'faq.q7': '¿Cómo cancelo mi suscripción?',
  'faq.a7': 'Un clic desde cualquier correo del resumen. Sin inicio de sesión requerido. Tus datos se eliminan en 24 horas.',

  'cta.title': '¿Listo para una mañana más inteligente?',
  'cta.subtitle': 'Utilizado por ingenieros de',
  'cta.button': 'Empezar gratis',

  // topics
  'topic_data_science_label': 'Ciencia de datos',
  'topic_data_science_desc': 'Estadística, análisis de datos y visualización',
  'topic_machine_learning_label': 'Aprendizaje automático',
  'topic_machine_learning_desc': 'Algoritmos, modelos y frameworks de ML',
  'topic_ai_research_label': 'Investigación en IA',
  'topic_ai_research_desc': 'Últimos artículos y avances científicos',
  'topic_agentic_ai_label': 'IA Agéntica',
  'topic_agentic_ai_desc': 'Agentes de IA, automatización y orquestación',
  'topic_mlops_label': 'MLOps',
  'topic_mlops_desc': 'Despliegue, monitorización y pipelines de ML',
  'topic_model_releases_label': 'Lanzamientos de modelos',
  'topic_model_releases_desc': 'Nuevos modelos de IA y actualizaciones',
  'topic_ai_industry_label': 'Industria de la IA',
  'topic_ai_industry_desc': 'Noticias empresariales, financiación y tendencias',
  'topic_tools_libraries_label': 'Herramientas y librerías',
  'topic_tools_libraries_desc': 'Herramientas para desarrolladores, SDKs y frameworks',

  // Missing UI keys
  'nav.home': 'Inicio',
  'nav.digest': 'Resumen',
  'nav.topics': 'Temas',
  'nav.profile': 'Perfil',
  'nav_domains': 'Temas',
  'nav_engine': 'Proceso',
  'nav_digest': 'Vista previa',
  'search_placeholder': 'Buscar en el resumen...',
  'focus_overline': 'Temas de Enfoque',
  'focus_title_1': 'Señales seleccionadas,',
  'focus_title_2': 'cero ruido.',
  'focus_desc': 'Monitoreamos los canales que importan, extrayendo solo inteligencia técnica accionable.',
  'engine_overline': 'El Motor',
  'engine_title_1': 'Cuatro agentes,',
  'engine_title_2': 'un pipeline.',
  'engine_desc': 'Nuestra secuencia de agentes de IA especializados se ejecuta de forma autónoma cada mañana a las 07:00 UTC.',
  'preview_overline': 'Señal Entrante',
  'preview_title_1': 'Explorar el',
  'preview_title_2': 'flujo diario',
  'cta_title_1': '¿Listo para estar',
  'cta_title_2': 'al día?',
  'cta_desc': 'Reciba su resumen diario de inteligencia a las 07:00 UTC.',
  'faq_overline': 'Preguntas frecuentes',
  'faq_title_1': 'Preguntas',
  'faq_title_2': 'frecuentes',
  'reading_time': 'min de lectura',
};

// ─────────────────────────────────────────────────────────────────────────────

const fr: TranslationMap = {
  'nav.features': 'Fonctionnalités',
  'nav.howItWorks': 'Comment ça marche',
  'nav.pricing': 'Tarifs',
  'nav.signIn': 'Se connecter',
  'nav.dashboard': 'Tableau de bord',
  'nav.signOut': 'Se déconnecter',

  'hero.headline': 'Gardez une longueur',
  'hero.subheadline': "d'avance.",
  'hero.description': 'Abonnez-vous pour recevoir un digest technique hebdomadaire autonome sur les lancements de modèles IA, percées de frameworks et articles de recherche fondamentaux les plus importants. Préparé par des agents spécialisés, livré dans votre boîte de réception.',
  'hero.emailPlaceholder': 'Entrez votre adresse e-mail',
  'hero.ctaButton': 'Recevoir mon briefing',
  'hero.successMessage': 'Abonnement réussi. Bienvenue.',
  'hero.errorMessage': 'Une erreur est survenue. Veuillez réessayer.',

  'features.title': 'Quatre agents. Un briefing parfait.',
  'features.subtitle': "Un pipeline autonome s'exécute chaque matin pour que vous ne manquiez rien d'essentiel.",
  'features.badge1': 'Agent Scraper',
  'features.badge2': 'Agent Filtre',
  'features.badge3': 'Zéro bruit',
  'features.desc1': "Parcourt plus de 200 sources — ArXiv, GitHub, TechCrunch et d'autres — chaque matin.",
  'features.desc2': 'Note chaque article par pertinence, déduplique et élimine le bruit.',
  'features.desc3': 'Livre uniquement ce qui correspond à vos sujets sélectionnés.',

  'footer.tagline': "L'intelligence, livrée chaque jour.",
  'footer.rights': '© 2025 NeuralBrief',
  'footer.privacyPolicy': 'Politique de confidentialité',
  'footer.terms': "Conditions d'utilisation",
  'footer.contact': 'Contact',
  'footer.emailPlaceholder': 'email@domaine.com',
  'footer.ctaButton': 'Abonné. À demain.',

  'profile.title': 'Votre profil',
  'profile.topics': 'Sujets',
  'profile.preferences': 'Préférences',
  'profile.bookmarks': 'Favoris',
  'profile.save': 'Enregistrer',
  'profile.saving': 'Enregistrement…',
  'profile.saved': 'Enregistré',
  'profile.logout': 'Se déconnecter',
  'profile.digestFrequency': 'Fréquence du digest',
  'profile.daily': 'Quotidien',
  'profile.weekly': 'Hebdomadaire',

  'auth.signInWithGoogle': 'Continuer avec Google',
  'auth.signingIn': 'Connexion en cours…',
  'auth.signOut': 'Se déconnecter',
  'auth.popupBlocked': 'Fenêtre pop-up bloquée. Autorisez les pop-ups et réessayez.',
  'auth.authError': "Échec de l'authentification. Veuillez réessayer.",
  'auth.loginRequired': 'Veuillez vous connecter pour continuer.',

  'bookmarks.title': 'Articles sauvegardés',
  'bookmarks.empty': "Aucun favori pour l'instant. Lisez des articles pour les sauvegarder ici.",
  'bookmarks.remove': 'Supprimer',
  'bookmarks.loginRequired': 'Connectez-vous pour voir vos favoris.',

  'engine.title': 'Le pipeline',
  'engine.description': "Quatre agents spécialisés s'exécutent en séquence chaque matin à 07:00 UTC.",
  'engine.step1': 'Agent Scraper — collecte de nouveaux articles depuis plus de 200 sources.',
  'engine.step2': 'Agent Filtre — note la pertinence et supprime les doublons.',
  'engine.step3': 'Agent Résumé — condense chaque article en deux phrases.',
  'engine.step4': 'Agent Email — assemble et envoie votre digest personnalisé via Gmail.',

  'faq.title': 'Questions fréquentes',
  'faq.q1': 'Quels sujets puis-je suivre ?',
  'faq.a1': 'Vous pouvez suivre la recherche en IA, les lancements de produits, les outils développeurs, les startups, la politique et bien plus.',
  'faq.q2': 'Quand le digest est-il livré ?',
  'faq.a2': 'Les digests sont envoyés à 07:00 UTC chaque matin, ou le lundi si vous préférez un rythme hebdomadaire.',
  'faq.q3': 'Comment les doublons sont-ils évités ?',
  'faq.a3': "L'Agent Filtre déduplique par URL et similarité sémantique avant la génération des résumés.",
  'faq.q4': 'Mes données Gmail sont-elles privées ?',
  'faq.a4': 'Nous envoyons uniquement des e-mails dans votre boîte de réception — nous ne lisons ni ne stockons vos messages Gmail.',
  'faq.q5': 'Puis-je changer mes sujets plus tard ?',
  'faq.a5': "Oui — ouvrez votre profil à tout moment pour ajouter ou supprimer des sujets. Les modifications s'appliquent dès le prochain digest.",
  'faq.q6': 'NeuralBrief est-il gratuit ?',
  'faq.a6': "Oui — le digest hebdomadaire principal est entièrement gratuit. Inscrivez-vous avec votre e-mail et commencez à recevoir des briefings sans aucun frais.",
  'faq.q7': 'Comment me désabonner ?',
  'faq.a7': "Un clic depuis n'importe quel e-mail de digest. Aucune connexion requise. Vos données sont supprimées sous 24 heures.",

  'cta.title': 'Prêt pour des matins plus intelligents ?',
  'cta.subtitle': 'Adopté par des ingénieurs chez',
  'cta.button': 'Commencer gratuitement',

  // topics
  'topic_data_science_label': 'Science des données',
  'topic_data_science_desc': 'Statistiques, analyse de données et visualisation',
  'topic_machine_learning_label': 'Apprentissage automatique',
  'topic_machine_learning_desc': 'Algorithmes, modèles et frameworks de ML',
  'topic_ai_research_label': 'Recherche en IA',
  'topic_ai_research_desc': 'Derniers articles et avancées scientifiques',
  'topic_agentic_ai_label': 'IA Agentique',
  'topic_agentic_ai_desc': 'Agents IA, automatisation et orchestration',
  'topic_mlops_label': 'MLOps',
  'topic_mlops_desc': 'Déploiement, surveillance et pipelines ML',
  'topic_model_releases_label': 'Sorties de modèles',
  'topic_model_releases_desc': 'Nouveaux modèles IA et mises à jour',
  'topic_ai_industry_label': "Industrie de l'IA",
  'topic_ai_industry_desc': 'Actualités business, financements et tendances',
  'topic_tools_libraries_label': 'Outils et bibliothèques',
  'topic_tools_libraries_desc': 'Outils développeurs, SDKs et frameworks',

  // Missing UI keys
  'nav.home': 'Accueil',
  'nav.digest': 'Digest',
  'nav.topics': 'Sujets',
  'nav.profile': 'Profil',
  'nav_domains': 'Sujets',
  'nav_engine': 'Pipeline',
  'nav_digest': 'Aperçu',
  'search_placeholder': 'Rechercher dans le digest...',
  'focus_overline': 'Domaines d\'intérêt',
  'focus_title_1': 'Signaux sélectionnés,',
  'focus_title_2': 'zéro bruit.',
  'focus_desc': 'Nous surveillons les canaux importants, en extrayant uniquement de l\'intelligence technique exploitable.',
  'engine_overline': 'Le Moteur',
  'engine_title_1': 'Quatre agents,',
  'engine_title_2': 'un pipeline.',
  'engine_desc': 'Notre séquence d\'agents d\'IA spécialisés s\'exécute de manière autonome chaque matin à 07h00 UTC.',
  'preview_overline': 'Signal entrant',
  'preview_title_1': 'Explorer le',
  'preview_title_2': 'flux quotidien',
  'cta_title_1': 'Prêt à garder',
  'cta_title_2': 'une longueur d\'avance?',
  'cta_desc': 'Recevez votre digest quotidien d\'intelligence à 07h00 UTC.',
  'faq_overline': 'FAQ',
  'faq_title_1': 'Questions',
  'faq_title_2': 'fréquentes',
  'reading_time': 'min de lecture',
};

// ─────────────────────────────────────────────────────────────────────────────

const hi: TranslationMap = {
  'nav.features': 'विशेषताएँ',
  'nav.howItWorks': 'यह कैसे काम करता है',
  'nav.pricing': 'मूल्य निर्धारण',
  'nav.signIn': 'साइन इन करें',
  'nav.dashboard': 'डैशबोर्ड',
  'nav.signOut': 'साइन आउट करें',

  'hero.headline': 'तकनीक की दुनिया में',
  'hero.subheadline': 'सबसे आगे रहें।',
  'hero.description': 'सबसे महत्वपूर्ण AI मॉडल रिलीज़, फ़्रेมवर्क सफलताओं और शोध पत्रों का साप्ताहिक स्वायत्त तकनीकी डाइजेस्ट प्राप्त करने के लिए सदस्यता लें। विशेष एजेंटों द्वारा तैयार, सीधे आपके इनबॉक्स में वितरित।',
  'hero.emailPlaceholder': 'अपना ईमेल पता दर्ज करें',
  'hero.ctaButton': 'मेरा ब्रीफ़िंग पाएँ',
  'hero.successMessage': 'सफलतापूर्वक सदस्यता ली। स्वागत है।',
  'hero.errorMessage': 'कुछ गलत हो गया। कृपया पुनः प्रयास करें।',

  'features.title': 'चार एजेंट। एक परफेक्ट ब्रीफ।',
  'features.subtitle': 'हर सुबह एक स्वायत्त पाइपलाइन चलती है ताकि आप कुछ भी न चूकें।',
  'features.badge1': 'स्क्रेपर एजेंट',
  'features.badge2': 'फ़िल्टर एजेंट',
  'features.badge3': 'शून्य शोर',
  'features.desc1': 'हर सुबह ArXiv, GitHub, TechCrunch और अन्य 200+ स्रोतों को खंगालता है।',
  'features.desc2': 'प्रत्येक लेख को प्रासंगिकता के आधार पर स्कोर करता है और डुप्लीकेट हटाता है।',
  'features.desc3': 'केवल वही सामग्री देता है जो आपके चुने गए विषयों से मेल खाती है।',

  'footer.tagline': 'बुद्धिमत्ता, हर दिन वितरित।',
  'footer.rights': '© 2025 NeuralBrief',
  'footer.privacyPolicy': 'गोपनीयता नीति',
  'footer.terms': 'सेवा की शर्तें',
  'footer.contact': 'संपर्क',
  'footer.emailPlaceholder': 'email@address.com',
  'footer.ctaButton': 'सदस्यता ले ली। कल मिलेंगे।',

  'profile.title': 'आपकी प्रोफ़ाइल',
  'profile.topics': 'विषय',
  'profile.preferences': 'प्राथमिकताएँ',
  'profile.bookmarks': 'बुकमार्क',
  'profile.save': 'परिवर्तन सहेजें',
  'profile.saving': 'सहेजा जा रहा है…',
  'profile.saved': 'सहेजा गया',
  'profile.logout': 'लॉग आउट',
  'profile.digestFrequency': 'डाइजेस्ट आवृत्ति',
  'profile.daily': 'दैनिक',
  'profile.weekly': 'साप्ताहिक',

  'auth.signInWithGoogle': 'Google से जारी रखें',
  'auth.signingIn': 'साइन इन हो रहा है…',
  'auth.signOut': 'साइन आउट करें',
  'auth.popupBlocked': 'पॉप-अप ब्लॉक हो गया। कृपया पॉप-अप की अनुमति दें और पुनः प्रयास करें।',
  'auth.authError': 'प्रमाणीकरण विफल। कृपया पुनः प्रयास करें।',
  'auth.loginRequired': 'जारी रखने के लिए कृपया साइन इन करें।',

  'bookmarks.title': 'सहेजे गए लेख',
  'bookmarks.empty': 'अभी कोई बुकमार्क नहीं। लेख पढ़ें और यहाँ सहेजें।',
  'bookmarks.remove': 'हटाएँ',
  'bookmarks.loginRequired': 'बुकमार्क देखने के लिए साइन इन करें।',

  'engine.title': 'पाइपलाइन',
  'engine.description': 'चार विशेष एजेंट हर सुबह 07:00 UTC पर क्रम से चलते हैं।',
  'engine.step1': 'स्क्रेपर एजेंट — 200+ स्रोतों से ताज़े लेख एकत्र करता है।',
  'engine.step2': 'फ़िल्टर एजेंट — प्रासंगिकता स्कोर करता है और डुप्लीकेट हटाता है।',
  'engine.step3': 'सारांश एजेंट — प्रत्येक लेख को दो वाक्यों में संक्षिप्त करता है।',
  'engine.step4': 'ईमेल एजेंट — आपका व्यक्तिगत डाइजेस्ट Gmail से भेजता है।',

  'faq.title': 'अक्सर पूछे जाने वाले प्रश्न',
  'faq.q1': 'मैं कौन से विषय फ़ॉलो कर सकता हूँ?',
  'faq.a1': 'AI शोध, उत्पाद लॉन्च, डेवलपर टूल, स्टार्टअप, नीति और बहुत कुछ।',
  'faq.q2': 'डाइजेस्ट कब भेजा जाता है?',
  'faq.a2': 'हर सुबह 07:00 UTC पर, या साप्ताहिक चुनने पर सोमवार को।',
  'faq.q3': 'डुप्लीकेट लेखों को कैसे रोका जाता है?',
  'faq.a3': 'फ़िल्टर एजेंट URL और अर्थपूर्ण समानता के आधार पर डुप्लीकेट हटाता है।',
  'faq.q4': 'क्या मेरा Gmail डेटा सुरक्षित है?',
  'faq.a4': 'हम केवल आपके इनबॉक्स में ईमेल भेजते हैं — आपके Gmail संदेश कभी नहीं पढ़ते।',
  'faq.q5': 'क्या मैं बाद में विषय बदल सकता हूँ?',
  'faq.a5': 'हाँ — किसी भी समय अपनी प्रोफ़ाइल खोलें। परिवर्तन अगले डाइजेस्ट से लागू होंगे।',
  'faq.q6': 'क्या NeuralBrief मुफ़्त है?',
  'faq.a6': 'हाँ — साप्ताहिक डाइजेस्ट बिल्कुल मुफ़्त है। अपना ईमेल दें और बिना किसी शुल्क के इंटेलिजेंस ब्रीफिंग पाना शुरू करें।',
  'faq.q7': 'मैं अनसब्सक्राइब कैसे करूँ?',
  'faq.a7': 'किसी भी डाइजेस्ट ईमेल से एक क्लिक में। लॉगिन की जरूरत नहीं। आपका डेटा 24 घंटे में हटा दिया जाता है।',

  'cta.title': 'एक स्मार्ट सुबह के लिए तैयार हैं?',
  'cta.subtitle': 'इन कंपनियों के इंजीनियर भरोसा करते हैं',
  'cta.button': 'मुफ़्त में शुरू करें',

  // topics
  'topic_data_science_label': 'डेटा विज्ञान',
  'topic_data_science_desc': 'सांख्यिकी, डेटा विश्लेषण और विज़ुअलाइज़ेशन',
  'topic_machine_learning_label': 'मशीन लर्निंग',
  'topic_machine_learning_desc': 'ML एल्गोरिदम, मॉडल और फ्रेमवर्क',
  'topic_ai_research_label': 'AI अनुसंधान',
  'topic_ai_research_desc': 'नवीनतम शोधपत्र और वैज्ञानिक सफलताएँ',
  'topic_agentic_ai_label': 'एजेंटिक AI',
  'topic_agentic_ai_desc': 'AI एजेंट, स्वचालन और ऑर्केस्ट्रेशन',
  'topic_mlops_label': 'MLOps',
  'topic_mlops_desc': 'ML डिप्लॉयमेंट, मॉनिटरिंग और पाइपलाइन',
  'topic_model_releases_label': 'मॉडल रिलीज़',
  'topic_model_releases_desc': 'नए AI मॉडल लॉन्च और अपडेट',
  'topic_ai_industry_label': 'AI उद्योग',
  'topic_ai_industry_desc': 'व्यापार समाचार, फंडिंग और रुझान',
  'topic_tools_libraries_label': 'टूल्स और लाइब्रेरी',
  'topic_tools_libraries_desc': 'डेवलपर टूल्स, SDK और फ्रेमवर्क',

  // Missing UI keys
  'nav.home': 'मुख्य पृष्ठ',
  'nav.digest': 'डाइजेस्ट',
  'nav.topics': 'विषय',
  'nav.profile': 'प्रोफ़ाइल',
  'nav_domains': 'विषय',
  'nav_engine': 'पाइपलाइन',
  'nav_digest': 'पूर्वावलोकन',
  'search_placeholder': 'ब्रीफ में खोजें...',
  'focus_overline': 'प्रमुख विषय',
  'focus_title_1': 'चयनित संकेत,',
  'focus_title_2': 'शून्य शोर।',
  'focus_desc': 'हम महत्वपूर्ण चैनलों की निगरानी करते हैं, केवल उपयोगी तकनीकी जानकारी निकालते हैं।',
  'engine_overline': 'इंजन',
  'engine_title_1': 'चार एजेंट,',
  'engine_title_2': 'एक पाइपलाइन।',
  'engine_desc': 'हमारे विशेष एआई एजेंटों का क्रम हर सुबह 07:00 UTC पर स्वचालित रूप से चलता है।',
  'preview_overline': 'आने वाले सिग्नल',
  'preview_title_1': 'दैनिक फ़ीड का',
  'preview_title_2': 'पता लगाएं',
  'cta_title_1': 'आगे रहने के लिए',
  'cta_title_2': 'तैयार हैं?',
  'cta_desc': 'हर सुबह 07:00 UTC पर अपना दैनिक डाइजेस्ट प्राप्त करें।',
  'faq_overline': 'अक्सर पूछे जाने वाले प्रश्न',
  'faq_title_1': 'अक्सर पूछे',
  'faq_title_2': 'जाने वाले प्रश्न',
  'reading_time': 'मिनट का पाठ',
};

// ─────────────────────────────────────────────────────────────────────────────

const zh: TranslationMap = {
  'nav.features': '功能特点',
  'nav.howItWorks': '工作原理',
  'nav.pricing': '定价',
  'nav.signIn': '登录',
  'nav.dashboard': '控制台',
  'nav.signOut': '退出登录',

  'hero.headline': '掌握前沿',
  'hero.subheadline': 'AI 动态。',
  'hero.description': '订阅以每周接收关于最重大的 AI 模型发布、框架突破和基础研究论文的自动化技术简报。由专业智能体筛选，直接送达您的收件箱。',
  'hero.emailPlaceholder': '请输入您的电子邮箱',
  'hero.ctaButton': '获取我的简报',
  'hero.successMessage': '订阅成功，欢迎您。',
  'hero.errorMessage': '出现错误，请重试。',

  'features.title': '四个智能体，一份完美简报。',
  'features.subtitle': '每天清晨，自动化流水线为您筛选最重要的资讯。',
  'features.badge1': '抓取智能体',
  'features.badge2': '过滤智能体',
  'features.badge3': '零噪音',
  'features.desc1': '每天早上爬取 ArXiv、GitHub、TechCrunch 等 200 余个来源。',
  'features.desc2': '对每篇文章进行相关性评分，去重并过滤低价值内容。',
  'features.desc3': '仅推送与您选择的主题匹配的内容。',

  'footer.tagline': '每日智能简报，准时送达。',
  'footer.rights': '© 2025 NeuralBrief',
  'footer.privacyPolicy': '隐私政策',
  'footer.terms': '服务条款',
  'footer.contact': '联系我们',
  'footer.emailPlaceholder': 'email@address.com',
  'footer.ctaButton': '订阅成功，明天见。',

  'profile.title': '个人资料',
  'profile.topics': '话题',
  'profile.preferences': '偏好设置',
  'profile.bookmarks': '收藏',
  'profile.save': '保存更改',
  'profile.saving': '保存中…',
  'profile.saved': '已保存',
  'profile.logout': '退出登录',
  'profile.digestFrequency': '简报频率',
  'profile.daily': '每日',
  'profile.weekly': '每周',

  'auth.signInWithGoogle': '使用 Google 继续',
  'auth.signingIn': '登录中…',
  'auth.signOut': '退出登录',
  'auth.popupBlocked': '弹窗被拦截，请允许弹窗后重试。',
  'auth.authError': '身份验证失败，请重试。',
  'auth.loginRequired': '请登录后继续。',

  'bookmarks.title': '已保存文章',
  'bookmarks.empty': '暂无收藏，开始阅读以保存文章。',
  'bookmarks.remove': '删除',
  'bookmarks.loginRequired': '请登录以查看您的收藏。',

  'engine.title': '处理流水线',
  'engine.description': '四个专用智能体每天早上 07:00 UTC 按顺序运行。',
  'engine.step1': '抓取智能体 — 从 200 余个精选来源采集最新文章。',
  'engine.step2': '过滤智能体 — 进行相关性评分并去除重复内容。',
  'engine.step3': '摘要智能体 — 将每篇文章提炼为两句话简报。',
  'engine.step4': '邮件智能体 — 生成您的个性化简报并通过 Gmail 发送。',

  'faq.title': '常见问题',
  'faq.q1': '我可以关注哪些话题？',
  'faq.a1': '可关注 AI 研究、产品发布、开发者工具、创业公司、政策等多种组合。',
  'faq.q2': '简报何时送达？',
  'faq.a2': '每天早上 07:00 UTC 发送，或选择每周一发送。',
  'faq.q3': '如何防止重复文章？',
  'faq.a3': '过滤智能体在生成摘要前通过 URL 和语义相似度去重。',
  'faq.q4': '我的 Gmail 数据安全吗？',
  'faq.a4': '我们仅向您的收件箱发送邮件，从不读取或存储您的 Gmail 邮件。',
  'faq.q5': '我之后可以更改话题吗？',
  'faq.a5': '可以 — 随时打开个人资料添加或删除话题，变更从下一期简报起生效。',
  'faq.q6': 'NeuralBrief 是免费的吗？',
  'faq.a6': '是的 — 每周核心简报完全免费。填写邮箱即可订阅，零费用接收情报简报。',
  'faq.q7': '如何取消订阅？',
  'faq.a7': '点击任意简报邮件中的退订链接即可，无需登录。您的数据将在 24 小时内删除。',

  'cta.title': '准备好迎接更智慧的每天早晨了吗？',
  'cta.subtitle': '受到这些公司工程师的信赖',
  'cta.button': '免费开始',

  // topics
  'topic_data_science_label': '数据科学',
  'topic_data_science_desc': '统计学、数据分析与可视化',
  'topic_machine_learning_label': '机器学习',
  'topic_machine_learning_desc': 'ML 算法、模型与框架',
  'topic_ai_research_label': 'AI 研究',
  'topic_ai_research_desc': '最新论文与突破性进展',
  'topic_agentic_ai_label': 'Agentic AI',
  'topic_agentic_ai_desc': 'AI 智能体、自动化与编排',
  'topic_mlops_label': 'MLOps',
  'topic_mlops_desc': 'ML 部署、监控与流水线',
  'topic_model_releases_label': '模型发布',
  'topic_model_releases_desc': '新 AI 模型发布与更新',
  'topic_ai_industry_label': 'AI 产业',
  'topic_ai_industry_desc': '商业资讯、融资动态与行业趋势',
  'topic_tools_libraries_label': '工具与库',
  'topic_tools_libraries_desc': '开发者工具、SDK 与框架',

  // Missing UI keys
  'nav.home': '首页',
  'nav.digest': '简报',
  'nav.topics': '话题',
  'nav.profile': '个人资料',
  'nav_domains': '专业领域',
  'nav_engine': '处理流程',
  'nav_digest': '简报预览',
  'search_placeholder': '搜索简报...',
  'focus_overline': '关注领域',
  'focus_title_1': '精选信号，',
  'focus_title_2': '零噪音。',
  'focus_desc': '我们监控关键渠道，仅提取具有可操作性的技术情报。',
  'engine_overline': '分析引擎',
  'engine_title_1': '四个智能体，',
  'engine_title_2': '一套流水线。',
  'engine_desc': '我们的专业 AI 智能体队列在每天早上 07:00 UTC 自动运行。',
  'preview_overline': '汇入信号',
  'preview_title_1': '探索',
  'preview_title_2': '每日动态',
  'cta_title_1': '准备好',
  'cta_title_2': '保持领先了吗？',
  'cta_desc': '在每天早上 07:00 UTC 接收您的每日智能简报。',
  'faq_overline': '常见问题',
  'faq_title_1': '常见',
  'faq_title_2': '问题解答',
  'reading_time': '分钟阅读',
};

// ─────────────────────────────────────────────────────────────────────────────

const ko: TranslationMap = {
  'nav.features': '기능',
  'nav.howItWorks': '작동 방식',
  'nav.pricing': '요금제',
  'nav.signIn': '로그인',
  'nav.dashboard': '대시보드',
  'nav.signOut': '로그아웃',

  'hero.headline': '기술의 흐름을',
  'hero.subheadline': '앞서 파악하세요.',
  'hero.description': '가장 중요한 AI 모델 출시, 프레임워크 혁신, 기초 연구 논문에 대한 주간 자율 기술 다이제스트를 받으려면 구독하세요. 전문 에이전트가 큐레이션하여 받은 편지함으로 직접 배달합니다.',
  'hero.emailPlaceholder': '이메일 주소를 입력하세요',
  'hero.ctaButton': '브리핑 받기',
  'hero.successMessage': '구독이 완료되었습니다. 환영합니다.',
  'hero.errorMessage': '오류가 발생했습니다. 다시 시도해 주세요.',

  'features.title': '네 개의 에이전트. 하나의 완벽한 브리핑.',
  'features.subtitle': '매일 아침 자동 파이프라인이 실행되어 중요한 정보를 놓치지 않게 합니다.',
  'features.badge1': '스크레이퍼 에이전트',
  'features.badge2': '필터 에이전트',
  'features.badge3': '노이즈 제로',
  'features.desc1': '매일 아침 ArXiv, GitHub, TechCrunch 등 200개 이상의 소스를 수집합니다.',
  'features.desc2': '각 기사의 관련성을 평가하고, 중복을 제거하며, 저품질 콘텐츠를 걸러냅니다.',
  'features.desc3': '선택한 주제와 일치하는 콘텐츠만 전달합니다.',

  'footer.tagline': '매일 아침, 인텔리전스가 도착합니다.',
  'footer.rights': '© 2025 NeuralBrief',
  'footer.privacyPolicy': '개인정보처리방침',
  'footer.terms': '이용약관',
  'footer.contact': '문의하기',
  'footer.emailPlaceholder': 'email@address.com',
  'footer.ctaButton': '구독 완료. 내일 봬요.',

  'profile.title': '내 프로필',
  'profile.topics': '주제',
  'profile.preferences': '환경 설정',
  'profile.bookmarks': '북마크',
  'profile.save': '변경 사항 저장',
  'profile.saving': '저장 중…',
  'profile.saved': '저장됨',
  'profile.logout': '로그아웃',
  'profile.digestFrequency': '다이제스트 빈도',
  'profile.daily': '매일',
  'profile.weekly': '매주',

  'auth.signInWithGoogle': 'Google로 계속하기',
  'auth.signingIn': '로그인 중…',
  'auth.signOut': '로그아웃',
  'auth.popupBlocked': '팝업이 차단되었습니다. 팝업을 허용하고 다시 시도해 주세요.',
  'auth.authError': '인증에 실패했습니다. 다시 시도해 주세요.',
  'auth.loginRequired': '계속하려면 로그인하세요.',

  'bookmarks.title': '저장된 기사',
  'bookmarks.empty': '아직 북마크가 없습니다. 기사를 읽고 여기에 저장해 보세요.',
  'bookmarks.remove': '삭제',
  'bookmarks.loginRequired': '북마크를 보려면 로그인하세요.',

  'engine.title': '파이프라인',
  'engine.description': '네 개의 전문 에이전트가 매일 오전 07:00 UTC에 순서대로 실행됩니다.',
  'engine.step1': '스크레이퍼 에이전트 — 200개 이상의 소스에서 최신 기사를 수집합니다.',
  'engine.step2': '필터 에이전트 — 관련성을 평가하고 중복을 제거합니다.',
  'engine.step3': '요약 에이전트 — 각 기사를 두 문장으로 압축합니다.',
  'engine.step4': '이메일 에이전트 — 개인화된 다이제스트를 Gmail로 발송합니다.',

  'faq.title': '자주 묻는 질문',
  'faq.q1': '어떤 주제를 팔로우할 수 있나요?',
  'faq.a1': 'AI 연구, 제품 출시, 개발자 도구, 스타트업, 정책 등 다양한 조합을 팔로우할 수 있습니다.',
  'faq.q2': '다이제스트는 언제 전달되나요?',
  'faq.a2': '매일 오전 07:00 UTC에 발송되며, 주간 선택 시 월요일에 발송됩니다.',
  'faq.q3': '중복 기사는 어떻게 방지하나요?',
  'faq.a3': '필터 에이전트가 URL 및 의미적 유사도를 기준으로 요약 생성 전에 중복을 제거합니다.',
  'faq.q4': '내 Gmail 데이터는 안전한가요?',
  'faq.a4': '받은 편지함에 이메일만 발송하며, Gmail 메시지를 읽거나 저장하지 않습니다.',
  'faq.q5': '나중에 주제를 변경할 수 있나요?',
  'faq.a5': '언제든지 프로필을 열어 주제를 추가하거나 제거할 수 있습니다. 변경 사항은 다음 다이제스트부터 적용됩니다.',
  'faq.q6': 'NeuralBrief는 무료인가요?',
  'faq.a6': '네 — 주간 핵심 다이제스트는 완전 무료입니다. 이메일만 등록하면 비용 없이 인텔리전스 브리핑을 받을 수 있습니다.',
  'faq.q7': '구독을 어떻게 취소하나요?',
  'faq.a7': '다이제스트 이메일에서 한 번의 클릭으로 취소할 수 있습니다. 로그인 불필요. 데이터는 24시간 내에 삭제됩니다.',

  'cta.title': '더 스마트한 아침을 시작할 준비가 되셨나요?',
  'cta.subtitle': '이 기업의 엔지니어들이 신뢰합니다',
  'cta.button': '무료로 시작하기',

  // topics
  'topic_data_science_label': '데이터 과학',
  'topic_data_science_desc': '통계, 데이터 분석 및 시각화',
  'topic_machine_learning_label': '머신러닝',
  'topic_machine_learning_desc': 'ML 알고리즘, 모델 및 프레임워크',
  'topic_ai_research_label': 'AI 연구',
  'topic_ai_research_desc': '최신 논문과 혁신적 연구 성과',
  'topic_agentic_ai_label': '에이전틱 AI',
  'topic_agentic_ai_desc': 'AI 에이전트, 자동화 및 오케스트레이션',
  'topic_mlops_label': 'MLOps',
  'topic_mlops_desc': 'ML 배포, 모니터링 및 파이프라인',
  'topic_model_releases_label': '모델 출시',
  'topic_model_releases_desc': '새로운 AI 모델 출시 및 업데이트',
  'topic_ai_industry_label': 'AI 산업',
  'topic_ai_industry_desc': '비즈니스 뉴스, 투자 동향 및 트렌드',
  'topic_tools_libraries_label': '도구 및 라이브러리',
  'topic_tools_libraries_desc': '개발자 도구, SDK 및 프레임워크',

  // Missing UI keys
  'nav.home': '홈',
  'nav.digest': '다이제스트',
  'nav.topics': '주제',
  'nav.profile': '프로필',
  'nav_domains': '분야',
  'nav_engine': '파이프라인',
  'nav_digest': '미리보기',
  'search_placeholder': '브리핑 검색...',
  'focus_overline': '집중 분야',
  'focus_title_1': '정밀한 신호,',
  'focus_title_2': '노이즈 제로.',
  'focus_desc': '우리는 중요한 채널들을 모니터링하여 실용적인 기술 정보만을 추출합니다.',
  'engine_overline': '분석 엔진',
  'engine_title_1': '네 개의 에이전트,',
  'engine_title_2': '하나의 파이프라인.',
  'engine_desc': '우리의 전문 AI 에이전트 프로세스는 매일 아침 07:00 UTC에 자율적으로 작동합니다.',
  'preview_overline': '유입 신호',
  'preview_title_1': '일일 스트림',
  'preview_title_2': '둘러보기',
  'cta_title_1': '앞서 나갈',
  'cta_title_2': '준비가 되셨나요?',
  'cta_desc': '매일 오전 07:00 UTC에 일일 인텔리전스 다이제스트를 받아보세요.',
  'faq_overline': '자주 묻는 질문',
  'faq_title_1': '자주 묻는',
  'faq_title_2': '질문들',
  'reading_time': '분 읽기',
};

// ─────────────────────────────────────────────────────────────────────────────

const hg={...en};const de={...en};const ja={...en};const it={...en};const pt={...en};const ru={...en};const ar={...en};const nl={...en};
const DICTIONARIES: Record<Language, TranslationMap> = { en, es, fr, hi, zh, ko, hg, de, ja, it, pt, ru, ar, nl };

// ─────────────────────────────────────────────────────────────────────────────

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

/**
 * Provides language switching and translation lookup to the component tree.
 * Translations are bundled inline — no network fetch required.
 */
export function LanguageProvider({ children }: { children: ReactNode }): React.JSX.Element {
  const [language, setLanguage] = useState<Language>('en');

  /**
   * Returns the translated string for `key` in the active language.
   * Falls back to the key itself when a translation is missing so the UI
   * always renders something meaningful.
   */
  const t = (key: string): string => DICTIONARIES[language]?.[key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

/** Hook to consume LanguageContext. Must be used inside LanguageProvider. */
export function useLanguage(): LanguageContextType {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageProvider;