import fs from 'fs';

const hg = `
const hg: TranslationMap = {
  'nav.features': 'Features',
  'nav.howItWorks': 'Kaise Kaam Karta Hai',
  'nav.pricing': 'Pricing',
  'nav.signIn': 'Sign In Karein',
  'nav.dashboard': 'Dashboard',
  'nav.signOut': 'Sign Out Karein',
  'hero.headline': 'AI Noise Se Bahar Niklein',
  'hero.subheadline': 'Personalized AI intelligence, bas kuch minutes mein.',
  'hero.description': 'NeuralBrief research papers, model releases, aur industry news ko monitor karta hai, aur unhe concise briefings mein convert karta hai jo aap easily padh sakein.',
  'hero.ctaPrimary': "Aaj Ki Briefing Dekhein",
  'hero.ctaSecondary': 'Ye Kaise Kaam Karta Hai',
  'hero.trustMetrics': '5-Min Read • 500+ Sources • Personalized Topics',
  'hero.trustSources': 'Research Papers • Open-Source Projects • Model Releases • Industry News',
  'hero.emailPlaceholder': 'Apna email address daalein',
  'hero.ctaButton': 'Meri Briefing Bhejein',
  'hero.successMessage': 'Successfully subscribe ho gaya. Welcome.',
  'hero.errorMessage': 'Kuch galat ho gaya. Please phir se try karein.',
  'features.title': 'Char Agents. Ek Perfect Brief.',
  'features.subtitle': 'Ek autonomous pipeline har subah run hoti hai taaki aap kuch miss na karein.',
  'features.badge1': 'Scraper Agent',
  'features.badge2': 'Filter Agent',
  'features.badge3': 'Zero Noise',
  'features.desc1': 'Har subah ArXiv, GitHub, TechCrunch jaise 200+ sources scan karta hai.',
  'features.desc2': 'Har article ki relevance score karta hai aur duplicates aur noise ko discard karta hai.',
  'features.desc3': 'Sirf wahi deliver karta hai jo aapke chosen topics se match kare.',
  'footer.tagline': 'Intelligence, rozana deliver ki gayi.',
  'footer.rights': '© 2025 NeuralBrief',
  'footer.privacyPolicy': 'Privacy Policy',
  'footer.terms': 'Terms of Service',
  'footer.contact': 'Contact',
  'footer.emailPlaceholder': 'email@address.com',
  'footer.ctaButton': 'Subscribed. Kal milte hain.',
  'profile.title': 'Aapki Profile',
  'profile.topics': 'Topics',
  'profile.preferences': 'Preferences',
  'profile.bookmarks': 'Bookmarks',
  'profile.save': 'Changes Save Karein',
  'profile.saving': 'Save ho raha hai…',
  'profile.saved': 'Save ho gaya',
  'profile.logout': 'Log Out',
  'profile.digestFrequency': 'Digest Frequency',
  'profile.daily': 'Daily',
  'profile.weekly': 'Weekly',
  'auth.signInWithGoogle': 'Google se Continue karein',
  'auth.signingIn': 'Sign in ho raha hai…',
  'auth.signOut': 'Sign Out',
  'auth.popupBlocked': 'Pop-up block ho gaya. Please allow karein aur phir try karein.',
  'auth.authError': 'Authentication fail ho gaya. Please phir try karein.',
  'auth.loginRequired': 'Continue karne ke liye please sign in karein.',
  'bookmarks.title': 'Saved Articles',
  'bookmarks.empty': 'Koi bookmark nahi. Articles padhna shuru karein aur yahan save karein.',
  'bookmarks.remove': 'Remove',
  'bookmarks.loginRequired': 'Bookmarks dekhne ke liye sign in karein.',
  'engine.title': 'The Pipeline',
  'engine.description': 'Char specialised agents har subah 07:00 UTC par sequence mein run hote hain.',
  'engine.step1': 'Scraper Agent — 200+ curated sources se fresh articles nikalta hai.',
  'engine.step2': 'Filter Agent — relevance score karta hai aur duplicates remove karta hai.',
  'engine.step3': 'Summary Agent — har article ko do sentences mein distill karta hai.',
  'engine.step4': 'Email Agent — aapka personalised digest banata aur bhejta hai.',
  'faq.title': 'Frequently Asked Questions',
  'faq.q1': 'Main kaun se topics follow kar sakta hoon?',
  'faq.a1': 'Aap AI research, product releases, startups aur bahut kuch follow kar sakte hain.',
  'faq.q2': 'Digest kab deliver hoti hai?',
  'faq.a2': 'Har subah 07:00 UTC par, ya Monday ko weekly format mein.',
  'faq.q3': 'Duplicate articles kaise prevent karte hain?',
  'faq.a3': 'Filter Agent summaries generate hone se pehle semantic similarity se deduplicate karta hai.',
  'faq.q4': 'Kya mera Gmail data private hai?',
  'faq.a4': 'Hum sirf aapko emails bhejte hain — aapke inbox messages kabhi nahi padhte.',
  'faq.q5': 'Kya main apne topics baad mein change kar sakta hoon?',
  'faq.a5': 'Haan — kisi bhi waqt profile mein jaa kar changes karein.',
  'faq.q6': 'Kya NeuralBrief free hai?',
  'faq.a6': 'Haan — core weekly digest bilkul free hai.',
  'faq.q7': 'Main unsubscribe kaise karoon?',
  'faq.a7': 'Digest email se sirf ek click mein.',
  'cta.title': 'Smarter morning ke liye ready hain?',
  'cta.subtitle': 'Top engineers ka bharosa',
  'cta.button': 'Free Shuru Karein',
  'topic_data_science_label': 'Data Science',
  'topic_data_science_desc': 'Statistics, data analysis aur visualization',
  'topic_machine_learning_label': 'Machine Learning',
  'topic_machine_learning_desc': 'ML algorithms, models aur frameworks',
  'topic_ai_research_label': 'AI Research',
  'topic_ai_research_desc': 'Latest papers aur breakthroughs',
  'topic_agentic_ai_label': 'Agentic AI',
  'topic_agentic_ai_desc': 'AI agents, automation aur orchestration',
  'topic_mlops_label': 'MLOps',
  'topic_mlops_desc': 'ML deployment, monitoring aur pipelines',
  'topic_model_releases_label': 'Model Releases',
  'topic_model_releases_desc': 'Naye AI model launches aur updates',
  'topic_ai_industry_label': 'AI Industry',
  'topic_ai_industry_desc': 'Business news, funding aur trends',
  'topic_tools_libraries_label': 'Tools & Libraries',
  'topic_tools_libraries_desc': 'Developer tools, SDKs aur frameworks',
  'nav.home': 'Home',
  'nav.digest': 'Digest',
  'nav.topics': 'Topics',
  'nav.profile': 'Profile',
  'nav_domains': 'Domains',
  'nav_engine': 'Pipeline',
  'nav_digest': 'Preview',
  'search_placeholder': 'Brief search karein...',
  'personalize_overline': 'Personalization Engine',
  'personalize_headline_1': 'Apni Khud Ki',
  'personalize_headline_2': 'AI Briefing Banayein',
  'personalize_desc': 'Aap signal control karte hain. Apne focus areas select karein aur humare agents aapke liye custom feed tayyar karenge.',
  'personalize_topics': 'Focus Areas',
  'personalize_language': 'Output Language',
  'personalize_relevance': 'Briefing Relevance',
  'personalize_feedback_none': 'NeuralBrief ko batayein aapke liye kya matter karta hai.',
  'personalize_feedback_some': 'NeuralBrief in signals ko prioritize kar raha hai.',
  'focus_overline': 'Focus Domains',
  'focus_title_1': 'Curated signals,',
  'focus_title_2': 'zero noise.',
  'focus_desc': 'Hum important channels monitor karte hain.',
  'how_overline': 'Our Process',
  'how_title_1': 'Hum Kaise',
  'how_title_2': 'Kaam Karte Hain',
  'how_desc': 'NeuralBrief AI news ko high-signal intelligence mein badalta hai.',
  'how_step1_title': 'Noise Monitor Karein',
  'how_step1_desc': 'Hum continuously sources monitor karte hain.',
  'how_step2_title': 'Signal Extract Karein',
  'how_step2_desc': 'Hum fluff aur duplicates ko remove karte hain.',
  'how_step3_title': 'Core Synthesize Karein',
  'how_step3_desc': 'Hum concise technical briefings banate hain.',
  'how_step4_title': 'Clarity Deliver Karein',
  'how_step4_desc': 'Final dispatch seedha aapke inbox mein.',
  'how_metrics_volume': '2.4M+',
  'how_metrics_volume_label': 'Documents Analyzed',
  'how_metrics_noise': '98%',
  'how_metrics_noise_label': 'Noise Filtered',
  'how_metrics_time': '12hrs',
  'how_metrics_time_label': 'Saved per User/Week',
  'engine_overline': 'The Architecture',
  'engine_title_1': 'Intelligence Engine',
  'engine_title_2': 'Ke Andar',
  'engine_desc': 'Har briefing ke peeche ek multi-stage pipeline hai.',
  'preview_overline': 'Inbound Signal',
  'preview_title_1': 'Daily Stream',
  'preview_title_2': 'Explore Karein',
  'cta_title_1': 'Aage rehne ke',
  'cta_title_2': 'liye ready hain?',
  'cta_desc': 'Apni daily digest receive karein 07:00 UTC par.',
  'faq_overline': 'FAQ',
  'faq_title_1': 'Frequently Asked',
  'faq_title_2': 'Questions',
  'reading_time': 'min read',
};
`;

const fileStr = fs.readFileSync('src/contexts/LanguageContext.tsx', 'utf-8');

const langObjects = {
  de: {
    name: 'German',
    dict: {
        'nav.features': 'Funktionen',
        'nav.howItWorks': 'Wie es funktioniert',
        'nav.pricing': 'Preise',
        'nav.signIn': 'Anmelden',
        'nav.dashboard': 'Dashboard',
        'nav.signOut': 'Abmelden',
        'hero.headline': 'Schneiden Sie durch den KI-Lärm',
        'hero.subheadline': 'Personalisierte KI-Intelligenz, geliefert in Minuten.',
        'hero.description': 'NeuralBrief überwacht Forschungsarbeiten und Branchennachrichten und wandelt sie in prägnante Briefings um.',
        'hero.ctaPrimary': "Heutiges Briefing ansehen",
        'hero.ctaSecondary': 'Wie es funktioniert',
        'hero.trustMetrics': '5-Min Lesezeit • 500+ Quellen',
        'hero.trustSources': 'Forschungsarbeiten • Open-Source-Projekte',
        'hero.emailPlaceholder': 'E-Mail-Adresse eingeben',
        'hero.ctaButton': 'Mein Briefing erhalten',
        'hero.successMessage': 'Erfolgreich abonniert.',
        'hero.errorMessage': 'Etwas ist schiefgelaufen. Bitte erneut versuchen.',
        'features.title': 'Vier Agenten. Ein perfektes Briefing.',
        'features.subtitle': 'Eine autonome Pipeline läuft jeden Morgen.',
        'features.badge1': 'Scraper-Agent',
        'features.badge2': 'Filter-Agent',
        'features.badge3': 'Null Lärm',
        'features.desc1': 'Durchsucht jeden Morgen 200+ Quellen.',
        'features.desc2': 'Bewertet jeden Artikel nach Relevanz und verwirft Lärm.',
        'features.desc3': 'Liefert nur das, was zu Ihren Themen passt.',
        'footer.tagline': 'Intelligenz, täglich geliefert.',
        'footer.rights': '© 2025 NeuralBrief',
        'footer.privacyPolicy': 'Datenschutzrichtlinie',
        'footer.terms': 'Nutzungsbedingungen',
        'footer.contact': 'Kontakt',
        'footer.emailPlaceholder': 'email@adresse.de',
        'footer.ctaButton': 'Abonniert. Bis morgen.',
        'profile.title': 'Ihr Profil',
        'profile.topics': 'Themen',
        'profile.preferences': 'Einstellungen',
        'profile.bookmarks': 'Lesezeichen',
        'profile.save': 'Änderungen speichern',
        'profile.saving': 'Speichern…',
        'profile.saved': 'Gespeichert',
        'profile.logout': 'Abmelden',
        'profile.digestFrequency': 'Häufigkeit',
        'profile.daily': 'Täglich',
        'profile.weekly': 'Wöchentlich',
        'auth.signInWithGoogle': 'Weiter mit Google',
        'auth.signingIn': 'Anmelden…',
        'auth.signOut': 'Abmelden',
        'auth.popupBlocked': 'Pop-up blockiert.',
        'auth.authError': 'Authentifizierung fehlgeschlagen.',
        'auth.loginRequired': 'Bitte anmelden, um fortzufahren.',
        'bookmarks.title': 'Gespeicherte Artikel',
        'bookmarks.empty': 'Noch keine Lesezeichen.',
        'bookmarks.remove': 'Entfernen',
        'bookmarks.loginRequired': 'Melden Sie sich an.',
        'engine.title': 'Die Pipeline',
        'engine.description': 'Vier spezialisierte Agenten laufen nacheinander.',
        'engine.step1': 'Scraper-Agent sammelt Artikel.',
        'engine.step2': 'Filter-Agent entfernt Duplikate.',
        'engine.step3': 'Summary-Agent fasst zusammen.',
        'engine.step4': 'Email-Agent sendet das Digest.',
        'faq.title': 'Häufig gestellte Fragen',
        'faq.q1': 'Welchen Themen kann ich folgen?',
        'faq.a1': 'Sie können beliebigen KI-Forschungen folgen.',
        'faq.q2': 'Wann wird das Digest geliefert?',
        'faq.a2': 'Täglich um 07:00 UTC.',
        'faq.q3': 'Wie verhindern Sie Duplikate?',
        'faq.a3': 'Der Filter-Agent dedupliziert nach URLs.',
        'faq.q4': 'Sind meine Gmail-Daten privat?',
        'faq.a4': 'Wir lesen keine Gmail-Nachrichten.',
        'faq.q5': 'Kann ich Themen später ändern?',
        'faq.a5': 'Ja, jederzeit.',
        'faq.q6': 'Ist NeuralBrief kostenlos?',
        'faq.a6': 'Das wöchentliche Digest ist völlig kostenlos.',
        'faq.q7': 'Wie melde ich mich ab?',
        'faq.a7': 'Mit einem Klick aus jeder E-Mail.',
        'cta.title': 'Bereit für einen intelligenteren Morgen?',
        'cta.subtitle': 'Von Ingenieuren vertraut bei',
        'cta.button': 'Kostenlos starten',
        'topic_data_science_label': 'Data Science',
        'topic_machine_learning_label': 'Maschinelles Lernen',
        'topic_ai_research_label': 'KI-Forschung',
        'topic_agentic_ai_label': 'Agentische KI',
        'topic_mlops_label': 'MLOps',
        'topic_model_releases_label': 'Modellveröffentlichungen',
        'topic_ai_industry_label': 'KI-Industrie',
        'topic_tools_libraries_label': 'Tools & Bibliotheken',
        'nav.home': 'Startseite',
        'nav.digest': 'Digest',
        'nav.topics': 'Themen',
        'nav.profile': 'Profil',
        'nav_domains': 'Bereiche',
        'nav_engine': 'Pipeline',
        'nav_digest': 'Vorschau',
        'search_placeholder': 'Suchen...',
        'personalize_overline': 'Personalisierung',
        'personalize_headline_1': 'Bauen Sie Ihr',
        'personalize_headline_2': 'KI-Briefing',
        'personalize_desc': 'Sie kontrollieren das Signal.',
        'personalize_topics': 'Fokusbereiche',
        'personalize_language': 'Sprache',
        'personalize_relevance': 'Relevanz',
        'personalize_feedback_none': 'Themen auswählen.',
        'personalize_feedback_some': 'Wir passen Ihren Feed an.',
        'focus_overline': 'Fokusdomänen',
        'focus_title_1': 'Kuratierte Signale,',
        'focus_title_2': 'null Lärm.',
        'focus_desc': 'Wir überwachen wichtige Kanäle.',
        'how_overline': 'Unser Prozess',
        'how_title_1': 'Wie wir',
        'how_title_2': 'arbeiten',
        'how_desc': 'NeuralBrief erledigt die harte Arbeit für Sie.',
        'how_step1_title': 'Lärm überwachen',
        'how_step1_desc': 'Wir überwachen ArXiv, GitHub usw.',
        'how_step2_title': 'Signal extrahieren',
        'how_step2_desc': 'Wir entfernen Duplikate.',
        'how_step3_title': 'Kern synthetisieren',
        'how_step3_desc': 'Wir fassen zusammen.',
        'how_step4_title': 'Klarheit liefern',
        'how_step4_desc': 'Zustellung in Ihren Posteingang.',
        'how_metrics_volume': '2.4M+',
        'how_metrics_volume_label': 'Dokumente analysiert',
        'how_metrics_noise': '98%',
        'how_metrics_noise_label': 'Lärm gefiltert',
        'how_metrics_time': '12h',
        'how_metrics_time_label': 'Gespart pro Woche',
        'engine_overline': 'Die Architektur',
        'engine_title_1': 'Inside',
        'engine_title_2': 'Engine',
        'engine_desc': 'Eine mehrstufige Intelligenz-Pipeline.',
        'preview_overline': 'Eingehendes Signal',
        'preview_title_1': 'Täglichen Stream',
        'preview_title_2': 'entdecken',
        'cta_title_1': 'Bereit',
        'cta_title_2': 'voraus zu bleiben?',
        'cta_desc': 'Erhalten Sie Ihr tägliches Digest.',
        'faq_overline': 'FAQ',
        'faq_title_1': 'Häufig gestellte',
        'faq_title_2': 'Fragen',
        'reading_time': 'min lesezeit',
    }
  },
  ja: {
    name: 'Japanese',
    dict: {
        'nav.features': '機能',
        'nav.howItWorks': '仕組み',
        'nav.pricing': '料金',
        'nav.signIn': 'サインイン',
        'nav.dashboard': 'ダッシュボード',
        'nav.signOut': 'サインアウト',
        'hero.headline': 'AIノイズを切り抜ける',
        'hero.subheadline': 'パーソナライズされたAI情報',
        'hero.description': 'NeuralBriefは、研究論文などを監視し、簡潔なブリーフィングに変換します。',
        'hero.ctaPrimary': "今日のブリーフィングを見る",
        'hero.ctaSecondary': '仕組み',
        'hero.trustMetrics': '5分の読書',
        'hero.trustSources': '研究論文 • オープンソース',
        'hero.emailPlaceholder': 'メールアドレス',
        'hero.ctaButton': 'ブリーフィングを受け取る',
        'hero.successMessage': '登録成功。',
        'hero.errorMessage': 'エラーが発生しました。',
        'features.title': '4つのエージェント。',
        'features.subtitle': '自律型パイプラインが毎朝実行されます。',
        'features.badge1': 'スクレイパー',
        'features.badge2': 'フィルター',
        'features.badge3': 'ゼロノイズ',
        'features.desc1': '毎朝200以上のソースをクロール。',
        'features.desc2': '関連性をスコア化。',
        'features.desc3': '選択したトピックのみを配信。',
        'footer.tagline': '毎日のインテリジェンス',
        'footer.rights': '© 2025 NeuralBrief',
        'footer.privacyPolicy': 'プライバシーポリシー',
        'footer.terms': '利用規約',
        'footer.contact': '連絡先',
        'footer.emailPlaceholder': 'email@address.com',
        'footer.ctaButton': '購読しました。',
        'profile.title': 'プロフィール',
        'profile.topics': 'トピック',
        'profile.preferences': '設定',
        'profile.bookmarks': 'ブックマーク',
        'profile.save': '保存',
        'profile.saving': '保存中…',
        'profile.saved': '保存済み',
        'profile.logout': 'ログアウト',
        'profile.digestFrequency': '頻度',
        'profile.daily': '毎日',
        'profile.weekly': '毎週',
        'auth.signInWithGoogle': 'Googleで続行',
        'auth.signingIn': 'サインイン中…',
        'auth.signOut': 'サインアウト',
        'auth.popupBlocked': 'ポップアップがブロックされました。',
        'auth.authError': '認証エラー',
        'auth.loginRequired': 'サインインしてください。',
        'bookmarks.title': '保存された記事',
        'bookmarks.empty': 'ブックマークなし',
        'bookmarks.remove': '削除',
        'bookmarks.loginRequired': 'サインインが必要です',
        'engine.title': 'パイプライン',
        'engine.description': '4つのエージェントが連携。',
        'engine.step1': 'スクレイパー',
        'engine.step2': 'フィルター',
        'engine.step3': '要約',
        'engine.step4': 'メール送信',
        'faq.title': 'よくある質問',
        'faq.q1': 'どのトピックをフォローできますか？',
        'faq.a1': 'AI研究などをフォローできます。',
        'faq.q2': 'いつ配信されますか？',
        'faq.a2': '毎朝07:00 UTC',
        'faq.q3': '重複はどう防ぎますか？',
        'faq.a3': 'URLで重複排除します。',
        'faq.q4': 'データはプライベートですか？',
        'faq.a4': '安全です。',
        'faq.q5': 'トピックは後で変更できますか？',
        'faq.a5': 'いつでも変更可能',
        'faq.q6': '無料ですか？',
        'faq.a6': '無料です',
        'faq.q7': '解除方法は？',
        'faq.a7': 'ワンクリック',
        'cta.title': '準備はいいですか？',
        'cta.subtitle': 'エンジニアからの信頼',
        'cta.button': '無料で開始',
        'topic_data_science_label': 'データサイエンス',
        'topic_machine_learning_label': '機械学習',
        'topic_ai_research_label': 'AI研究',
        'topic_agentic_ai_label': '自律AI',
        'topic_mlops_label': 'MLOps',
        'topic_model_releases_label': 'モデルリリース',
        'topic_ai_industry_label': 'AI産業',
        'topic_tools_libraries_label': 'ツール＆ライブラリ',
        'nav.home': 'ホーム',
        'nav.digest': 'ダイジェスト',
        'nav.topics': 'トピック',
        'nav.profile': 'プロフィール',
        'nav_domains': 'ドメイン',
        'nav_engine': 'パイプライン',
        'nav_digest': 'プレビュー',
        'search_placeholder': '検索...',
        'personalize_overline': 'パーソナライズ',
        'personalize_headline_1': 'あなた自身の',
        'personalize_headline_2': 'ブリーフィング',
        'personalize_desc': 'シグナルをコントロール',
        'personalize_topics': 'フォーカス',
        'personalize_language': '言語',
        'personalize_relevance': '関連性',
        'personalize_feedback_none': '選択してください。',
        'personalize_feedback_some': 'フィードを調整中',
        'focus_overline': 'フォーカス領域',
        'focus_title_1': 'キュレーションされた信号、',
        'focus_title_2': 'ゼロノイズ。',
        'focus_desc': '監視しています',
        'how_overline': 'プロセス',
        'how_title_1': '私たちの',
        'how_title_2': '働き方',
        'how_desc': 'ハードワーク',
        'how_step1_title': '監視',
        'how_step1_desc': '継続的に監視',
        'how_step2_title': '抽出',
        'how_step2_desc': '重複を削除',
        'how_step3_title': '合成',
        'how_step3_desc': '技術的な要約',
        'how_step4_title': '配信',
        'how_step4_desc': '受信トレイに',
        'how_metrics_volume': '2.4M+',
        'how_metrics_volume_label': '分析済み',
        'how_metrics_noise': '98%',
        'how_metrics_noise_label': 'ノイズ除去',
        'how_metrics_time': '12h',
        'how_metrics_time_label': '節約された時間',
        'engine_overline': 'アーキテクチャ',
        'engine_title_1': 'インテリジェンス',
        'engine_title_2': 'エンジン',
        'engine_desc': 'マルチステージ',
        'preview_overline': 'シグナル',
        'preview_title_1': '探索',
        'preview_title_2': 'ストリーム',
        'cta_title_1': '準備',
        'cta_title_2': '完了？',
        'cta_desc': 'ダイジェストを受信',
        'faq_overline': 'FAQ',
        'faq_title_1': 'よくある',
        'faq_title_2': '質問',
        'reading_time': '分',
    }
  },
  it: { name: 'Italian', dict: { 'nav.features': 'Caratteristiche', 'nav.howItWorks': 'Come funziona' } },
  pt: { name: 'Portuguese', dict: { 'nav.features': 'Recursos', 'nav.howItWorks': 'Como funciona' } },
  ru: { name: 'Russian', dict: { 'nav.features': 'Особенности', 'nav.howItWorks': 'Как это работает' } },
  ar: { name: 'Arabic', dict: { 'nav.features': 'الميزات', 'nav.howItWorks': 'كيف يعمل' } },
  nl: { name: 'Dutch', dict: { 'nav.features': 'Kenmerken', 'nav.howItWorks': 'Hoe het werkt' } },
};

let output = fileStr;

const injectStr = `
${hg}

${Object.keys(langObjects).map(langCode => {
    return `
const ${langCode}: TranslationMap = new Proxy(en, {
  get: (target, prop) => {
    const custom = ${JSON.stringify(langObjects[langCode].dict)};
    if (typeof prop === 'string' && custom[prop]) return custom[prop];
    if (typeof prop === 'string' && target[prop]) return '[' + '${langCode.toUpperCase()}' + '] ' + target[prop];
    return target[prop];
  }
});
`;
}).join('\n')}
`;

output = output.replace(/type Language = 'en' \| 'es' \| 'fr' \| 'hi' \| 'zh' \| 'ko';/, "type Language = 'en' | 'es' | 'fr' | 'hi' | 'zh' | 'ko' | 'hg' | 'de' | 'ja' | 'it' | 'pt' | 'ru' | 'ar' | 'nl';");

output = output.replace(/const ko: TranslationMap = \{[\s\S]+?\};/, (match) => {
    return match + "\n" + injectStr;
});

output = output.replace(/const translations: Record<Language, TranslationMap> = \{ en, es, fr, hi, zh, ko \};/, "const translations: Record<Language, TranslationMap> = { en, es, fr, hi, zh, ko, hg, de, ja, it, pt, ru, ar, nl };");

fs.writeFileSync('src/contexts/LanguageContext.tsx', output);
